server:
  port: 8081

spring:
  application:
    name: shiro
  datasource:
    #    url: jdbc:mysql://47.98.59.193:3306/study?serverTimeZone=Asia/Shanghai&CharacterEncoding=UTF-8
    #    url: jdbc:mysql://localhost:3306/xweb?serverTimeZone=Asia/Shanghai&CharacterEncoding=UTF-8
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.11.128:5432/xweb
    username: ppdream
    password: 123ABCdef*
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
#    host: 47.98.59.193 # Redis服务器地址
    host: 192.168.11.128 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123ABCdef* # Redis服务器连接密码（默认为空）
    database: 0 # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

mybatis:
  type-aliases-package: com.ppdream.xweb.entity
  mapper-locations: classpath:com/**/mapper/*.xml

saltNo: 8
hashNo: 1024

logging:
  level:
    #    root: debug
    com.wx.selfblog.dao: warn

# 自定义jwt key
jwt:
  tokenHeader: Authorization # JWT存储的请求头
  secret: mySecret # JWT加解密使用的密钥
  expiration: 604800 # JWT的超期限时间(60*60*24)
  tokenHead: Bearer # JWT负载中拿到开头

# 上传文件存储位置
upload:
  blogDir: F:/ppdream/blogSaveDir # 上传的文件存储位置